duisburg_bible/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
import mysite.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mysite.views.index, name="index"),
    path('about/', mysite.views.about, name='about'),
    path('songs/', include('songbook.urls'), name="songbook"),
    path('notes/', include('note.urls'), name="notes"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

note/urls.py
from . import views
from django.urls import include, path

app_name = 'note'

urlpatterns = [
    path('', views.allnotes, name='allnotes'),
    path('<slug:slug>', views.detail, name='detail')
]

songbook/urls.py
from . import views
from django.urls import path, include

app_name = 'songbook'

urlpatterns = [
    path('', views.allsongs, name="allsongs"),
    path('<slug:slug>', views.detail, name='detail')
]

mysite/models.py
from django.db import models

# Create your models here.

note/models.py
from django.db import models
from django.urls import reverse

class Note(models.Model):
    title = models.CharField(max_length=100, blank=True)
    date = models.DateField()
    meeting = models.CharField(max_length=100)
    author = models.CharField(max_length=50)
    body = models.TextField()
    slug = models.SlugField(default="", null=False)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"slug": self.slug})
    

songbook/models.py
from django.db import models
from django.urls import reverse

class Song(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField(default="", null=False)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"slug": self.slug})

mysite/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'mysite/index.html')

def about(request):
    return render(request, 'mysite/about.html')

note/views.py
from django.shortcuts import render, get_object_or_404
from .models import Note

def allnotes(request):
    notes = Note.objects.all()
    return render(request, 'note/allnotes.html', {'notes':notes})

def detail(request, slug):
    note = get_object_or_404(Note, slug=slug)
    return render(request, 'note/detail.html', {'note': note})

songbook/views.py
from django.shortcuts import render, get_object_or_404
from .models import Song

def allsongs(request):
    songs = Song.objects.all().order_by('title').values()
    return render(request, 'songbook/allsongs.html', {'songs':songs})

def detail(request, slug):
    song = get_object_or_404(Song, slug=slug)
    return render(request, 'songbook/detail.html', {'song':song})

mysite/templates/mysite/about.html
{% extends 'mysite/base.html' %}

{% load static %}

{% block content %}

<div class="containter">
    <head>
      <h1 class="font-weight-bold text-center pt-5">About</h1>
      <h3 class="text-center mb-4">This website</h3>
    </head>
  </div>
    
  <div class="container p-2">
  <body>
    <div class="row gx-4 gy-4 p-4 justify-content-center">
      <div class="col-12 col-xxl-11 px-3 py-3 text-center">
        <p>
            We wanted to make it easier for everyone to access the worship lyrics. The songs are being 
            complied and listed in alphabetical order in the 
          <a href="{% url 'songbook:allsongs' %}">Songbook</a>.
        </p>
        <p>
          There are some people that like to take notes, and we really appreciate that!
          So we've made a home for them in <a href="{% url 'note:allnotes' %}">Notes</a>.
          Just talk to Hanna about uploading them! 
        </p>
        <p>
            We also have the <a href="{% static 'mysite/Sept-Nov24.pdf' %}">Bible Plan</a>
            which you can also download or just open right here on the website. And if you've 
            been wanting to read the commentary on the book of <a href="{% static 'mysite/Revelation.pdf' %}">Revelations</a>, 
            knock yourself out!
        </p>
      </div>
    </div>
  
  </body>
  </div>

{% endblock %}

mysite/templates/mysite/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags --> 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <!-- Custom CSS-->
    <link rel="stylesheet" href="{% static 'mysite/custom.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">   


    <link rel="icon" type="image/png" href="{% static 'mysite/BibleStudy.png' %}">
    <title>Duisburg Bible Study</title>

    <style>
      p {font-size: 1.3em;}
      p a {font-size: 1em;}
      a {font-size: 1.5em;}
      h1 {font-size: 3.75em;}
      h2 {font-size: 3.0em;}
      h3 {font-size: 2.25em;}
      h4 {font-size: 2.12em;}
      h5 {font-size: 1.75em;}
      h6 {font-size: 1.5em;}

      blockquote {
        background-color: #ededed;
        margin: 10px auto;
        padding: 15px;
        border-radius: 5px;
      }
      blockquote p::before {
        content: '\201C';
      }
      blockquote p::after {
        content: '\201D';
      }

      div.para {line-height: 1.8;}
    </style>

  </head>
  <body style="background-color:rgb(255, 255, 255)">
    <nav class="navbar navbar-expand-md navbar-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">
          <img src="{% static 'mysite/BibleStudy.png' %}" width="40" height="40" class="d-inline-block align-top">
          <span style="font-size: 1.2em;">Duisburg Bible Study</span> 
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
          <ul class="navbar-nav mb-2 mb-lg-0">
            <div class="dropdown">
              <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" style="font-size: 1.2em;" aria-expanded="false">
                Reading
              </button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% static 'mysite/Sept-Nov24.pdf' %} " style="font-size: 1.1em;">Bible Plan</a></li>
                <li><a class="dropdown-item" href="{% static 'mysite/Revelations-11.pdf' %}" style="font-size: 1.1em;">Revelations</a></li>
              </ul>
            </div>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'note:allnotes' %}" style="font-size: 1.2em;">Notes</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'songbook:allsongs' %}" style="font-size: 1.2em;">Songbook</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    {% block content %}{% endblock %}

    <!-- CDN stuff -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
  </body>
  <footer class="text-muted py-5">
    <div class="container text-center align-end">
        <a href="{% url 'about' %}">About</a>
     <p>© Hanna Song {% now "Y"%}</p>
    </div>
  </footer>
</html>

mysite/templates/mysite/index.html
{% extends 'mysite/base.html' %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row align-items-center justify-content-center py-5">
        <div class="col-11 col-lg-8 col-xl-7">
            <img src="{% static 'mysite/LBaptism.jpeg' %}" class="img-fluid rounded">
        </div>
        <div class="col-11 col-lg-4 col-xl-5 my-3">
            <h2>
                Hey ya'll!
            </h2>
            <br>
            <p>
                This webiste is a small spot where we can collect notes and find song lyrics. 
                You'll find everything up in the top right. 
            </p>
            <p>
                If anyone wants to submit notes or song lyrics, let Hanna know!
                She's in charge of keeping the website running.
            </p>
        </div>
    </div>
</div>

{% endblock %}

note/templates/note/allnotes.html
{% extends 'mysite/base.html' %}

{% load markdown_extras %}
{% load static %}

{% block content %}

<div class="container text-center">
    <h1 class="font-weight-bold text-center py-5">Notes</h1>


<div class="container-fluid">
    <div class="row" data-masonry='{"percentPosition": true }'>
        {% for note in notes %}
            <div class="col-lg-4 col-md-6">
                <a href="{% url 'note:detail' note.slug %}">
                    <h4 style="font-size: 1.5em;">{{ note.title }}</h4>
                </a>
                <h6 class="text-muted">{{ note.date|date:'M d Y'|upper }}</h6>
                <p>{{ note.body|markdown|striptags|truncatechars:125 }}</p>
            </div>

        {% endfor %}
    </div>

</div>

</div>



{% endblock %}

note/templates/note/detail.html
{% extends 'mysite/base.html' %}

{% load markdown_extras %}
{% load static %}

{% block content %}

<div class="container p-4">
    <h1 class="mt-5">{{ note.title }}</h1>
    <h6 class="text-muted">{{ note.date|date:'F jS Y'}}</h6>
    <div class="para col-12 col-xxl-11 px-3 py-3">
        <p>{{ note.body|markdown|safe }}</p>        
    </div>    


</div>

{% endblock %}

songbook/templates/songbook/allsongs.html
{% extends 'mysite/base.html' %}

{% load static %}

{% block content %}

<div class="container text-center">
    <h1 class="font-weight-bold text-center py-5">Songbook</h1>



    <div class="container-fluid">
        <div class="row">
            {% for song in songs %}
                <div class="col-10 my-3">
                    <a href="{% url 'songbook:detail' song.slug %}">
                        <h4 class="text-start" style="font-size: 1.5em;">{{ song.title }}</h4>
                    </a>
                </div>

            {% endfor %}
        </div>
    </div>

</div>

{% endblock %}

songbook/templates/songbook/detail.html
{% extends 'mysite/base.html' %}

{% load markdown_extras %}
{% load static %}

{% block content %}

<div class="container p-4">
    <div class="row justify-content-center">
        <div class="col-12">
            <h1 class="text-center mt-5">{{ song.title }}</h1>
            <div class="text-center para px-3 py-3">
                <p>{{ song.body|markdown|safe }}</p>
            </div>
        </div>
    </div>
    
</div>

{% endblock %}

songbook/templates/songbook/detail_1.html
{% extends 'mysite/base.html' %}

{% load static %}

{% block content %}


<div class="container">
    <a class="nav-link" href="{% url 'songbook:allsongs' %}" style="font-size: 1.2em;">Back to Songbook</a>
</div>


<div class="container p-4">
    <div class="row justify-content-center">
        <div class="col-12">
            <h1 class="text-center mt-5">{{ song.title }}</h1>
            <div class="text-center para px-3 py-3">
                <p>{{ song.body|safe }}</p>
            </div>
        </div>
    </div>
    
</div>
    

{% endblock %}